### PR TITLE
Add more dependencies for installation

### PR DESCRIPTION
**Pull request by segadora**
I needed those to make it work on Linux Mint 18

### CODE REVIEW

**Comment by Lin-Buo-Ren** [comment]
According to Debian Policy, `build-essential` package (and possibly including, `gcc`) shouldn't be listed in package's build dependencies.

Please reply if anything wrong with this decision, though.

**Comment by Lin-Buo-Ren** [comment]
UPDATE: according to [Package relationships](https://www.debian.org/doc/debian-policy/ch-source.html#s-pkg-relations) section in the Debian Policy Manual:

```
It is not necessary to explicitly specify build-time relationships on a minimal set of packages that are always needed to compile, link and put in a Debian package a standard "Hello World!" program written in C or C++. The required packages are called build-essential, and an informational list can be found in /usr/share/doc/build-essential/list (which is contained in the build-essential package).[13] 

[13]
Rationale:

    This allows maintaining the list separately from the policy documents (the list does not need the kind of control that the policy documents do).

    Having a separate package allows one to install the build-essential packages on a machine, as well as allowing other packages such as tasks to require installation of the build-essential packages using the depends relation.

    The separate package allows bug reports against the list to be categorized separately from the policy management process in the BTS.

```

**Comment by Lin-Buo-Ren** [comment]
Apologies for misunderstanding your pull request, you're changing the README instruction instead of the Debian control file.  However we should instead use `mk-build-deps` to install and manage build dependencies, so this PR will still remain closed.

**Comment by segadora** [comment]
I installed it by compiling it not installing a Debian file.

I don't know if build-essensials is needed, but it complained about some gcc wasn't installed

**Comment by Lin-Buo-Ren** [comment]
I'll fix the README in the near future and will post the results here.

**Comment by Lin-Buo-Ren** [comment]
Hi, now the [README](https://github.com/slacka/WinUSB) has been updated with a cleaner way to build & install WinUSB in Debian-based distributions.  The `build-essential` dependency is implicitly included during the build dependency installation process however I may decide to explicitly mention it in the Build-Depends field in the near future.

The actual commit that does the change: https://github.com/slacka/WinUSB/commit/ea27c9641de3c83da1169442e9ff51efb3973fc4

**Comment by segadora** [comment]
Cool thanks

**Pull request closed without merging**
